CREATE SCHEMA IF NOT EXISTS `oficina` DEFAULT CHARACTER SET utf8;

USE OFICINA;

CREATE TABLE IF NOT EXISTS `OFICINA`.`PESSOA` (
  `IDPESSOA` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `ENDERECO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDPESSOA`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OFICINA`.`CLIENTE` (
  `IDCLIENTE` INT NOT NULL AUTO_INCREMENT,
  `IDPESSOA` INT NOT NULL,
  PRIMARY KEY (`IDCLIENTE`, `IDPESSOA`),
  INDEX `fk_Cliente_Pessoa_idx` (`IDPESSOA` ASC),
  CONSTRAINT `fk_Cliente_Pessoa`
    FOREIGN KEY (`IDPESSOA`)
    REFERENCES `OFICINA`.`PESSOA` (`IDPESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OFICINA`.`EQUIPE` (
  `IDEQUIPE` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDEQUIPE`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OFICINA`.`MECANICOS` (
  `IDMECANICO` INT NOT NULL AUTO_INCREMENT,
  `ESPECIALIDADE` VARCHAR(45) NOT NULL,
  `IDPESSOA` INT NOT NULL,
  `IDEQUIPE` INT NOT NULL,
  PRIMARY KEY (`IDMECANICO`, `IDPESSOA`, `IDEQUIPE`),
  INDEX `fk_Mecânicos_Pessoa1_idx` (`IDPESSOA` ASC),
  INDEX `fk_Mecânicos_Equipe1_idx` (`IDEQUIPE` ASC),
  CONSTRAINT `fk_Mecânicos_Pessoa1`
    FOREIGN KEY (`IDPESSOA`)
    REFERENCES `OFICINA`.`PESSOA` (`IDPESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecânicos_Equipe1`
    FOREIGN KEY (`IDEQUIPE`)
    REFERENCES `OFICINA`.`EQUIPE` (`IDEQUIPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OFICINA`.`VEICULOS` (
  `IDVEICULO` INT NOT NULL AUTO_INCREMENT,
  `MODELO` VARCHAR(45) NOT NULL,
  `ANO` INT NOT NULL,
  `PLACA` VARCHAR(45) NOT NULL,
  `IDCLIENTE` INT NOT NULL,
  PRIMARY KEY (`IDVEICULO`, `IDCLIENTE`),
  INDEX `fk_Veículos_Cliente1_idx` (`IDCLIENTE` ASC),
  CONSTRAINT `fk_Veículos_Cliente1`
    FOREIGN KEY (`IDCLIENTE`)
    REFERENCES `OFICINA`.`CLIENTE` (`IDCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OFICINA`.`ORDEMSERVICO` (
  `NROOS` INT NOT NULL AUTO_INCREMENT,
  `IDVEICULO` INT NOT NULL,
  `IDEQUIPE` INT NOT NULL,
  `DTEMISSAO` DATE NOT NULL,
  `STATUS` ENUM('N', 'I', 'C') NOT NULL,
  `VALOR` FLOAT NOT NULL,
  `DTCONCLUSAO` DATE NULL,
  PRIMARY KEY (`NROOS`, `IDVEICULO`, `IDEQUIPE`),
  INDEX `fk_Veículos_has_Equipe_Equipe1_idx` (`IDEQUIPE` ASC),
  INDEX `fk_Veículos_has_Equipe_Veículos1_idx` (`IDVEICULO` ASC),
  CONSTRAINT `fk_Veículos_has_Equipe_Veículos1`
    FOREIGN KEY (`IDVEICULO`)
    REFERENCES `OFICINA`.`VEICULOS` (`IDVEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veículos_has_Equipe_Equipe1`
    FOREIGN KEY (`IDEQUIPE`)
    REFERENCES `OFICINA`.`EQUIPE` (`IDEQUIPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OFICINA`.`MAODEOBRA` (
  `idMO` INT NOT NULL auto_increment,
  `NOME` VARCHAR(45) NOT NULL,
  `VALOR` FLOAT NOT NULL,
  PRIMARY KEY (`idMO`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OFICINA`.`MATERIAIS` (
  `IDMATERIAL` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `VALOR` FLOAT NOT NULL,
  PRIMARY KEY (`IDMATERIAL`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OFICINA`.`SERVICO` (
  `IDSERVICO` INT NOT NULL AUTO_INCREMENT,
  `IDMO` INT NOT NULL,
  `IDMATERIAL` INT NULL,
  `VALOR` FLOAT NOT NULL,
  PRIMARY KEY (`IDSERVICO`, `IDMO`, `IDMATERIAL`),
  INDEX `fk_Serviços_has_Materiais_idx` (`IDMATERIAL` ASC),
  INDEX `fk_Serviços_has_MAODEOBRA_idx` (`IDMO` ASC),
  CONSTRAINT `fk_Serviços_has_Materiais_Serviços1`
    FOREIGN KEY (`IDMO`)
    REFERENCES `OFICINA`.`MAODEOBRA` (`idMO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Serviços_has_Materiais`
    FOREIGN KEY (`IDMATERIAL`)
    REFERENCES `OFICINA`.`MATERIAIS` (`IDMATERIAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `OFICINA`.`SERVICOSOS` (
  `NROOS` INT NOT NULL,
  `IDSERVICO` INT NOT NULL,
  PRIMARY KEY (`NROOS`, `IDSERVICO`),
  INDEX `fk_Ordem de serviço_has_Serviço_idx` (`IDSERVICO` ASC),
  INDEX `fk_Ordem de serviço_has_Serviço_OS_idx` (`NROOS` ASC),
  CONSTRAINT `fk_Ordem de serviço_has_Serviço_Ordem de serviço1`
    FOREIGN KEY (`NROOS`)
    REFERENCES `OFICINA`.`ORDEMSERVICO` (`NROOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de serviço_has_Serviço_Serviço1`
    FOREIGN KEY (`IDSERVICO`)
    REFERENCES `OFICINA`.`SERVICO` (`IDSERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;