/*1. Nro de serviços nas OS's iniciadas e não finalizadas */
SELECT 
	OS.NROOS,
    COUNT(IDSERVICO) AS NRODESERVICOS,
    CONCAT(OS.IDVEICULO, ' - ', VEI.MODELO) AS VEICULO,
    OS.VALOR
FROM ORDEMSERVICO OS
JOIN SERVICOSOS SOS ON SOS.NROOS = OS.NROOS 
JOIN VEICULOS VEI ON VEI.IDVEICULO = OS.IDVEICULO
WHERE
	OS.STATUS = 'N'
GROUP BY NROOS;

/*2. Pessoas cadastradas que são mecânicos e clientes */
SELECT 
	P.IDPESSOA,
    MEC.IDMECANICO,
    CLI.IDCLIENTE,
    P.NOME,
    MEC.ESPECIALIDADE
FROM PESSOA P
JOIN MECANICOS MEC ON MEC.IDPESSOA = P.IDPESSOA
JOIN CLIENTE CLI ON CLI.IDPESSOA = P.IDPESSOA;

/*3. Quantidade de OS iniciada e não finalizada que cada mecânico está envolvido pela equipe*/
SELECT 
	CONCAT(MEC.IDMECANICO, ' - ', P.NOME) AS MECANICO,
	COUNT(OS.NROOS) AS QTDOS
FROM ORDEMSERVICO OS
JOIN EQUIPE EQ ON EQ.IDEQUIPE = OS.IDEQUIPE
JOIN MECANICOS MEC ON MEC.IDEQUIPE = OS.IDEQUIPE
JOIN PESSOA P ON P.IDPESSOA = MEC.IDPESSOA
WHERE OS.STATUS = 'N'
GROUP BY 1
ORDER BY MEC.IDMECANICO;

/*4. Mecânicos envolvidos em mais de duas OS em aberto */ 
SELECT 
	CONCAT(MEC.IDMECANICO, ' - ', P.NOME) AS MECANICO,
	COUNT(OS.NROOS) AS QTDOS
FROM ORDEMSERVICO OS
JOIN EQUIPE EQ ON EQ.IDEQUIPE = OS.IDEQUIPE
JOIN MECANICOS MEC ON MEC.IDEQUIPE = OS.IDEQUIPE
JOIN PESSOA P ON P.IDPESSOA = MEC.IDPESSOA
WHERE OS.STATUS = 'N'
GROUP BY 1
HAVING COUNT(OS.NROOS) > 2
ORDER BY MEC.IDMECANICO;